spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://changeme-auth-server/realms/your-realm/protocol/openid-connect/certs" # changeme

spring:
  application:
    name: ubk-backend
  # --- DATASOURCE CONFIGURATION ---
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ubk_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  # --- JPA CONFIGURATION ---
  jpa:
    hibernate:
      ddl-auto: update # Use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # --- REDIS CONFIGURATION ---
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  # --- FLYWAY CONFIGURATION ---
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    kg.gov.mtsdr.ubk: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  api-docs.enabled: true
  swagger-ui.enabled: true
  show-actuator: true
  info:
    title: UBK Social Benefits API
    version: v0.0.1
    description: API for the "Үй-бүлөгө көмөк" social benefits system.
